# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Wed Mar  6 13:25:35 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ConfigureDialog(object):
    def setupUi(self, ConfigureDialog):
        ConfigureDialog.setObjectName(_fromUtf8("ConfigureDialog"))
        ConfigureDialog.resize(529, 274)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ConfigureDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(ConfigureDialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.identifierLineEdit = QtGui.QLineEdit(self.groupBox)
        self.identifierLineEdit.setObjectName(_fromUtf8("identifierLineEdit"))
        self.horizontalLayout.addWidget(self.identifierLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.localTab = QtGui.QWidget()
        self.localTab.setObjectName(_fromUtf8("localTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.localTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.localTab)
        self.label_3.setMinimumSize(QtCore.QSize(71, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.localLineEdit = QtGui.QLineEdit(self.localTab)
        self.localLineEdit.setStyleSheet(_fromUtf8("selection-color: red;\n"
"color: green"))
        self.localLineEdit.setObjectName(_fromUtf8("localLineEdit"))
        self.horizontalLayout_3.addWidget(self.localLineEdit)
        self.previousLocationLabel = QtGui.QLabel(self.localTab)
        self.previousLocationLabel.setEnabled(False)
        self.previousLocationLabel.setMaximumSize(QtCore.QSize(0, 0))
        self.previousLocationLabel.setObjectName(_fromUtf8("previousLocationLabel"))
        self.horizontalLayout_3.addWidget(self.previousLocationLabel)
        self.localDirectoryCheckBox = QtGui.QCheckBox(self.localTab)
        self.localDirectoryCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.localDirectoryCheckBox.setObjectName(_fromUtf8("localDirectoryCheckBox"))
        self.horizontalLayout_3.addWidget(self.localDirectoryCheckBox)
        self.localButton = QtGui.QPushButton(self.localTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.localButton.setFont(font)
        self.localButton.setObjectName(_fromUtf8("localButton"))
        self.horizontalLayout_3.addWidget(self.localButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.copyToWorkflowCheckBox = QtGui.QCheckBox(self.localTab)
        self.copyToWorkflowCheckBox.setObjectName(_fromUtf8("copyToWorkflowCheckBox"))
        self.horizontalLayout_4.addWidget(self.copyToWorkflowCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.localTab, _fromUtf8(""))
        self.pmrTab = QtGui.QWidget()
        self.pmrTab.setObjectName(_fromUtf8("pmrTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pmrTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.pmrTab)
        self.label_5.setMinimumSize(QtCore.QSize(71, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pmrLineEdit = QtGui.QLineEdit(self.pmrTab)
        self.pmrLineEdit.setObjectName(_fromUtf8("pmrLineEdit"))
        self.horizontalLayout_5.addWidget(self.pmrLineEdit)
        self.pmrButton = QtGui.QPushButton(self.pmrTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pmrButton.setFont(font)
        self.pmrButton.setObjectName(_fromUtf8("pmrButton"))
        self.horizontalLayout_5.addWidget(self.pmrButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.pmrTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.imageSourceTypeComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageSourceTypeComboBox.sizePolicy().hasHeightForWidth())
        self.imageSourceTypeComboBox.setSizePolicy(sizePolicy)
        self.imageSourceTypeComboBox.setObjectName(_fromUtf8("imageSourceTypeComboBox"))
        self.imageSourceTypeComboBox.addItem(_fromUtf8(""))
        self.imageSourceTypeComboBox.addItem(_fromUtf8(""))
        self.imageSourceTypeComboBox.addItem(_fromUtf8(""))
        self.imageSourceTypeComboBox.addItem(_fromUtf8(""))
        self.imageSourceTypeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.imageSourceTypeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(ConfigureDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.identifierLineEdit)
        self.label_3.setBuddy(self.localLineEdit)
        self.label_5.setBuddy(self.pmrLineEdit)
        self.label_6.setBuddy(self.imageSourceTypeComboBox)

        self.retranslateUi(ConfigureDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ConfigureDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ConfigureDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigureDialog)

    def retranslateUi(self, ConfigureDialog):
        ConfigureDialog.setWindowTitle(_translate("ConfigureDialog", "Configure - Image Source", None))
        self.label.setText(_translate("ConfigureDialog", "Identifier:", None))
        self.label_3.setText(_translate("ConfigureDialog", "Location:", None))
        self.previousLocationLabel.setText(_translate("ConfigureDialog", "rubbish", None))
        self.localDirectoryCheckBox.setText(_translate("ConfigureDialog", "Directory:", None))
        self.localButton.setText(_translate("ConfigureDialog", "...", None))
        self.copyToWorkflowCheckBox.setText(_translate("ConfigureDialog", "Copy to workflow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.localTab), _translate("ConfigureDialog", "Local file system", None))
        self.label_5.setText(_translate("ConfigureDialog", "Location:", None))
        self.pmrButton.setText(_translate("ConfigureDialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pmrTab), _translate("ConfigureDialog", "Physiome Model Repository", None))
        self.label_6.setText(_translate("ConfigureDialog", "Image Source Type:", None))
        self.imageSourceTypeComboBox.setItemText(0, _translate("ConfigureDialog", "from file extension", None))
        self.imageSourceTypeComboBox.setItemText(1, _translate("ConfigureDialog", "png (*.png)", None))
        self.imageSourceTypeComboBox.setItemText(2, _translate("ConfigureDialog", "jpg (*.jpg, *.jpeg)", None))
        self.imageSourceTypeComboBox.setItemText(3, _translate("ConfigureDialog", "TIFF (*.tiff)", None))
        self.imageSourceTypeComboBox.setItemText(4, _translate("ConfigureDialog", "DICOM (*.dcm)", None))

