# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Fri Jun 14 13:09:47 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ConfigureDialog(object):
    def setupUi(self, ConfigureDialog):
        ConfigureDialog.setObjectName("ConfigureDialog")
        ConfigureDialog.resize(529, 274)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ConfigureDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(ConfigureDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.identifierLineEdit = QtGui.QLineEdit(self.groupBox)
        self.identifierLineEdit.setObjectName("identifierLineEdit")
        self.horizontalLayout.addWidget(self.identifierLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.localTab = QtGui.QWidget()
        self.localTab.setObjectName("localTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.localTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.localTab)
        self.label_3.setMinimumSize(QtCore.QSize(71, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.localLineEdit = QtGui.QLineEdit(self.localTab)
        self.localLineEdit.setStyleSheet("selection-color: red;\n"
"color: green")
        self.localLineEdit.setObjectName("localLineEdit")
        self.horizontalLayout_3.addWidget(self.localLineEdit)
        self.previousLocationLabel = QtGui.QLabel(self.localTab)
        self.previousLocationLabel.setEnabled(False)
        self.previousLocationLabel.setMaximumSize(QtCore.QSize(0, 0))
        self.previousLocationLabel.setObjectName("previousLocationLabel")
        self.horizontalLayout_3.addWidget(self.previousLocationLabel)
        self.localDirectoryCheckBox = QtGui.QCheckBox(self.localTab)
        self.localDirectoryCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.localDirectoryCheckBox.setObjectName("localDirectoryCheckBox")
        self.horizontalLayout_3.addWidget(self.localDirectoryCheckBox)
        self.localButton = QtGui.QPushButton(self.localTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.localButton.setFont(font)
        self.localButton.setObjectName("localButton")
        self.horizontalLayout_3.addWidget(self.localButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.copyToWorkflowCheckBox = QtGui.QCheckBox(self.localTab)
        self.copyToWorkflowCheckBox.setObjectName("copyToWorkflowCheckBox")
        self.horizontalLayout_4.addWidget(self.copyToWorkflowCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.localTab, "")
        self.pmrTab = QtGui.QWidget()
        self.pmrTab.setObjectName("pmrTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pmrTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.pmrTab)
        self.label_5.setMinimumSize(QtCore.QSize(71, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.pmrLineEdit = QtGui.QLineEdit(self.pmrTab)
        self.pmrLineEdit.setObjectName("pmrLineEdit")
        self.horizontalLayout_5.addWidget(self.pmrLineEdit)
        self.pmrButton = QtGui.QPushButton(self.pmrTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pmrButton.setFont(font)
        self.pmrButton.setObjectName("pmrButton")
        self.horizontalLayout_5.addWidget(self.pmrButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.pmrTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.imageSourceTypeComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageSourceTypeComboBox.sizePolicy().hasHeightForWidth())
        self.imageSourceTypeComboBox.setSizePolicy(sizePolicy)
        self.imageSourceTypeComboBox.setObjectName("imageSourceTypeComboBox")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.imageSourceTypeComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.imageSourceTypeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(ConfigureDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.identifierLineEdit)
        self.label_3.setBuddy(self.localLineEdit)
        self.label_5.setBuddy(self.pmrLineEdit)
        self.label_6.setBuddy(self.imageSourceTypeComboBox)

        self.retranslateUi(ConfigureDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ConfigureDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ConfigureDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigureDialog)

    def retranslateUi(self, ConfigureDialog):
        ConfigureDialog.setWindowTitle(QtGui.QApplication.translate("ConfigureDialog", "Configure - Image Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ConfigureDialog", "Identifier:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ConfigureDialog", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.previousLocationLabel.setText(QtGui.QApplication.translate("ConfigureDialog", "rubbish", None, QtGui.QApplication.UnicodeUTF8))
        self.localDirectoryCheckBox.setText(QtGui.QApplication.translate("ConfigureDialog", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.localButton.setText(QtGui.QApplication.translate("ConfigureDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.copyToWorkflowCheckBox.setText(QtGui.QApplication.translate("ConfigureDialog", "Copy to workflow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.localTab), QtGui.QApplication.translate("ConfigureDialog", "Local file system", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ConfigureDialog", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.pmrButton.setText(QtGui.QApplication.translate("ConfigureDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pmrTab), QtGui.QApplication.translate("ConfigureDialog", "Physiome Model Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ConfigureDialog", "Image Source Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(0, QtGui.QApplication.translate("ConfigureDialog", "from file extension", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(1, QtGui.QApplication.translate("ConfigureDialog", "png (*.png)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(2, QtGui.QApplication.translate("ConfigureDialog", "jpg (*.jpg, *.jpeg)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(3, QtGui.QApplication.translate("ConfigureDialog", "TIFF (*.tiff)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSourceTypeComboBox.setItemText(4, QtGui.QApplication.translate("ConfigureDialog", "DICOM (*.dcm)", None, QtGui.QApplication.UnicodeUTF8))

