# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/logrecord.ui'
#
# Created: Mon Nov 24 11:44:20 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LogRecord(object):
    def setupUi(self, LogRecord):
        LogRecord.setObjectName("LogRecord")
        LogRecord.resize(678, 307)
        LogRecord.setMinimumSize(QtCore.QSize(400, 200))
        LogRecord.setMaximumSize(QtCore.QSize(1000, 600))
        self.gridLayout_2 = QtGui.QGridLayout(LogRecord)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.history = QtGui.QLabel(LogRecord)
        self.history.setObjectName("history")
        self.gridLayout.addWidget(self.history, 0, 0, 1, 1)
        self.information_table = QtGui.QTableWidget(LogRecord)
        self.information_table.setEnabled(True)
        self.information_table.setMouseTracking(False)
        self.information_table.setAutoFillBackground(False)
        self.information_table.setInputMethodHints(QtCore.Qt.ImhNone)
        self.information_table.setFrameShadow(QtGui.QFrame.Raised)
        self.information_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.information_table.setTabKeyNavigation(False)
        self.information_table.setProperty("showDropIndicator", False)
        self.information_table.setDragDropOverwriteMode(False)
        self.information_table.setAlternatingRowColors(False)
        self.information_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.information_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.information_table.setCornerButtonEnabled(False)
        self.information_table.setRowCount(0)
        self.information_table.setColumnCount(3)
        self.information_table.setObjectName("information_table")
        self.information_table.setColumnCount(3)
        self.information_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.information_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.information_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.information_table.setHorizontalHeaderItem(2, item)
        self.information_table.horizontalHeader().setVisible(True)
        self.information_table.horizontalHeader().setCascadingSectionResizes(True)
        self.information_table.horizontalHeader().setDefaultSectionSize(75)
        self.information_table.horizontalHeader().setHighlightSections(True)
        self.information_table.horizontalHeader().setMinimumSectionSize(75)
        self.information_table.horizontalHeader().setSortIndicatorShown(True)
        self.information_table.horizontalHeader().setStretchLastSection(True)
        self.information_table.verticalHeader().setVisible(False)
        self.information_table.verticalHeader().setDefaultSectionSize(20)
        self.information_table.verticalHeader().setHighlightSections(False)
        self.information_table.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout.addWidget(self.information_table, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtGui.QPushButton(LogRecord)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.detailsButton = QtGui.QPushButton(LogRecord)
        self.detailsButton.setObjectName("detailsButton")
        self.horizontalLayout.addWidget(self.detailsButton)
        spacerItem = QtGui.QSpacerItem(328, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeWindowButton = QtGui.QPushButton(LogRecord)
        self.closeWindowButton.setObjectName("closeWindowButton")
        self.horizontalLayout.addWidget(self.closeWindowButton)
        spacerItem1 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(LogRecord)
        QtCore.QObject.connect(self.closeWindowButton, QtCore.SIGNAL("clicked()"), LogRecord.close)
        QtCore.QObject.connect(self.information_table, QtCore.SIGNAL("itemDoubleClicked(QTableWidgetItem*)"), self.detailsButton.click)
        QtCore.QMetaObject.connectSlotsByName(LogRecord)

    def retranslateUi(self, LogRecord):
        LogRecord.setWindowTitle(QtGui.QApplication.translate("LogRecord", "Log Record", None, QtGui.QApplication.UnicodeUTF8))
        self.history.setText(QtGui.QApplication.translate("LogRecord", "History:", None, QtGui.QApplication.UnicodeUTF8))
        self.information_table.setSortingEnabled(True)
        self.information_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("LogRecord", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.information_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("LogRecord", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.information_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("LogRecord", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("LogRecord", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.detailsButton.setText(QtGui.QApplication.translate("LogRecord", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.closeWindowButton.setText(QtGui.QApplication.translate("LogRecord", "Close", None, QtGui.QApplication.UnicodeUTF8))

